version: '3.8'

services:
  stem-player:
    image: nginx:alpine
    container_name: stem-player
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Development server with live reload
  dev-server:
    image: node:18-alpine
    container_name: stem-player-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npx live-server --port=3000 --host=0.0.0.0 --open=/
    profiles:
      - development

networks:
  default:
    name: stem-player-network
